id: fhir.us.example
canonical: http://hl7.org/fhir/us/example
name: ExampleIG
title: "HL7 FHIR Implementation Guide: Example IG Release 1 - US Realm | STU1"
description: An example IG that exercises many of the fields in a SUSHI configuration
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
publisher:
  name: HL7 International - US Realm Steering Committee
  url: http://www.hl7.org/Special/committees/usrealm/index.cfm
  email: usrsc@lists.HL7.org
dependencies:
  hl7.fhir.us.core: 3.1.0
template: hl7.fhir.template#0.0.5