name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.73.0
          TARGET_REPO: FSHSchool/FSHSchool.github.io
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: fshschool.org
