name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install docsy prerequisites
        run: npm install postcss-cli autoprefixer

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.74.3
          HUGO_EXTENDED: true
          TARGET_REPO: FSHSchool/FSHSchool.github.io
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: fshschool.org
